name: "Unit Test"

on: [push,pull_request]

jobs:
  unit_test:
    name: Unit Test
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: "1.16"

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build
        run: make build

      - name: Test
        run: make test
